language: node_js
node_js:
- '0.10'
before_script:
- npm install
- grunt
notifications:
  email: true
deploy:
  provider: heroku
  app: doodles-io
  on: master
  api_key:
    secure: cmjGoZqcxCPPO/Ho6Y75rxgbGaQGWGx64VC/4pxNKF5VVQsMH0JlWgm4FX52oZoDCW7wbbMDP9Dm6/RAk5Az1nqqP8fGeSiLGnNWnIK2v1FrdiFd6VhqUbCYCOL0URje9Ynd40nWs56qhXTnLh3dnGpju6uqglsdx0PT1rqRo4o=
