language: node_js
branches:
  only:
    - master
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli
install: npm install --ignore-scripts
before_script:
- grunt test
notifications:
  email: true
